version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:17"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
