name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Replace with your desired Node.js version
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Node.js dependencies
      run: npm install
    - name: Run Python tests
      run: |
        pip install pytest
        pytest
    - name: Run Node.js tests
      run: npm test
